# Generated by Django 5.0.7 on 2024-07-17 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_nidslog_rename_uploaded_at_cloudlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudlog',
            old_name='timestamp',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='nidslog',
            old_name='timestamp',
            new_name='logged_at',
        ),
    ]
