# Generated by Django 5.0.7 on 2024-07-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_rename_timestamp_cloudlog_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudlog',
            name='file_path',
            field=models.CharField(default='default/path', max_length=255),
        ),
        migrations.AlterField(
            model_name='cloudlog',
            name='activity',
            field=models.CharField(max_length=255),
        ),
    ]
