# Generated by Django 5.0.7 on 2024-07-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_cloudlog_file_path_alter_cloudlog_activity'),
    ]

    operations = [
    ]
