# Generated by Django 5.0.7 on 2024-07-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_cloudlog_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudlog',
            old_name='uploaded_at',
            new_name='timestamp',
        ),
    ]
