# Generated by Django 5.0.7 on 2024-07-17 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_rename_uploaded_at_cloudlog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudlog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
