# Generated by Django 5.0.7 on 2024-07-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_cloudlog_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudlog',
            name='uploaded_at',
        ),
    ]
